### PR TITLE
Pass parent props into mapStateToProps

### PR DESCRIPTION
**Pull request by ide**
Addresses part of #52 by passing the parent props into mapStateWithProps.

### CODE REVIEW

**Comment by jhollingworth** [comment]
This doesn't actually check whether we are passing in `props`, see #36

**Comment by gaearon** [comment]
Thanks for the effort! I'm closing in favor of #59 which is a more complete solution.

**Comment by gaearon** [comment]
A version of this is released in 0.9.0, please verify.

**Comment by ide** [comment]
Sweet, thank you guys! Will test it out sometime today.

**Pull request closed without merging**
