### PR TITLE
Update Docs

### PR DESCRIPTION
**Pull request by jlogsdon**
Here's my proposed structure for the documentation. I'm including the original docs from Redux for reference as I move forward. The very top should have a brief "quick start" example, and the sub sections will go into more detail about each.

### CODE REVIEW

**Comment by gaearon** [comment]
This looks good to me.

**Comment by jlogsdon** [comment]
Cool. I will work on filling out all the sections today/tomorrow.

**Comment by gaearon** [comment]
Thanks, I really appreciate it.

**Comment by Keats** [comment]
@jlogsdon don't forget to look at #1 and #16 so you don't write documentations for something that's going to be removed/changed

**Comment by gaearon** [comment]
@Keats @jlogsdon 

While #1 and #16 are important, it's more important to document the existing APIs right. I'm releasing Redux 1.0 very soon, and I'm going to have examples using React Redux 0.2.1. When we figure #16 out, we'll rewrite the docs, but it might take another week or so. Documenting 0.2.1 is still very important because lots of projects depend on it.

**Comment by jlogsdon** [comment]
Thanks for pointing those out, but I am going to focus on the existing API for the reasons @gaearon said. The new API isn't quite ready, and having docs of the stable release will be very important for the Redux 1.0 release.

I'm working on expanding some of the sections right now and will have something to push up here today.

**Comment by jlogsdon** [comment]
Here we go. The "Child must be a function" section needs to be expanded, but I am not familiar enough with the issue myself and couldn't find any resources about it specifically. If I can get pointed to either the React issue or a fiddle showing the issue I can fill that part out.

**Comment by gaearon** [comment]
Awesome, thanks.

**Pull request merged**
